---
- name: mount data filesystem
  become: yes
  command: >
    /usr/bin/mount "{{ usb_device }}3" /mnt

- name: create efi and data mount points
  become: yes
  file:
    path: '/mnt/boot/EFI'
    state: directory
    mode: '0755'
  
- name: deploy qubinode custom kickstart files
  become: yes
  template:
    src:  "{{ ks_file }}.j2"
    dest: "/mnt/{{ ks_file }}"
    mode: '0644'

- name: check if RHEL iso file exists
  stat: 
    path: "{{ rhel_iso_loc }}"
  register: iso_exists

- name: copy RHEL {{ iso_file }} file to usb device
  become: yes
  copy:
    src: "{{ rhel_iso_loc }}"
    dest: "/mnt/{{ iso_file }}"
    mode: '0644'
  when: iso_exists|bool
  

- name: check if RHEL qcow file exists
  stat: 
    path: "{{ qcow_image_loc }}"
  register: qcow_exists

- name: copy RHEL qcow file to usb device
  become: yes
  copy:
    src: "{{  qcow_image_loc }}"
    dest: "/mnt/{{ qcow_image_file }}"
    mode: '0644'
  when: qcow_exists|bool

- name: unmount data filesystem
  become: yes
  command: >
    /usr/bin/umount "{{ usb_device }}2"
  ignore_errors: True