---
- name: create data boot partition
  become: yes
  command: /usr/sbin/parted -s "{{ usb_device }}" mkpart primary 551MiB 100%

- name: format data filesystem
  become: yes
  command: /usr/sbin/mkfs.ext4 "{{ usb_device }}"2 -f

# - name: label the data partition filesystem
#   become: yes
#   command: xfs_admin -L qbusbdata "{{ usb_device }}2"

- name: label the data partition filesystem
  become: yes
  command: e2label  "{{ usb_device }}2" qbusbdata 