---
# format_disks file for qubinode-usb-imager
- name: read usb device information 
  become: yes
  parted: 
    device: "{{ usb_device }}"
    unit: MiB
  register: disk_info

- name: unmount usb qubinode device
  become: yes
  mount:
    path: "{{ usb_device }}{{ item.num }}"
    state: absent
  with_items:
    - "{{ disk_info.partitions }}"
  
- name: remove all partitions from disk 
  parted:
    device: "{{ usb_device }}"
    number: "{{ item.num }}"
    state: absent
  with_items:
    - "{{ disk_info.partitions }}"

- name: tell the OS the paritions has change
  become: yes
  command: >
    sudo partprobe
  register: partprobe_result
  ignore_errors: True

- name: create efi boot partition
  become: yes
  parted:
    label: gpt
    unit: MiB
    device: "{{ usb_device }}"
    number: 1
    flags: [ boot ]
    part_start: 1MiB
    part_end: 201MiB
    state: present

- name: create legacy boot partition
  become: yes
  parted:
    label: gpt
    unit: MiB
    device: "{{ usb_device }}"
    number: 2
    flags: [ boot,legacy_boot,bios_grub ]
    part_start: 201MiB
    part_end: 401MiB
    state: present

- name: create data partition
  become: yes
  parted:
    label: gpt
    unit: MiB
    device: "{{ usb_device }}"
    number: 3
    part_start: 401MiB
    part_end: 100%
    state: present

- name: format efi boot grub filesystem
  become: yes
  filesystem:
    fstype: vfat
    dev: "{{ usb_device }}1"
    force: yes

- name: format legacy boot grub filesystem
  become: yes
  filesystem:
    fstype: ext4
    dev: "{{ usb_device }}2"
    force: yes 

- name: format data partition filesystem
  become: yes
  filesystem:
    fstype: ext4
    dev: "{{ usb_device }}3"
    force: yes