---
# format_disks file for qubinode-usb-imager
- name: read usb device information 
  become: yes
  parted: 
    device: "{{ usb_device }}"
    unit: MiB
  register: disk_info

- name: unmount usb qubinode device
  become: yes
  mount:
    path: "{ usb_device }}{{ item.num }}"
    state: absent
  with_items:
    - "{{ disk_info.partitions }}"
  
- name: remove all partitions from disk 
  parted:
    device: "{{ usb_device }}"
    number: "{{ item.num }}"
    state: absent
  with_items:
    - "{{ disk_info.partitions }}"

- name: tell the OS the paritions has change
  become: yes
  command: >
    sudo partprobe
  ignore_errors: True

- name: create efi grub boot disk partition
  become: yes
  parted:
    label: gpt
    device: "{{ usb_device }}"
    number: 1
    state: present
    part_type: primary
    part_end: 1024MiB 
    flags: [ boot, legacy_boot ]

- name: create data boot disk partition
  become: yes
  parted:
     label: gpt
     device: "{{ usb_device }}"
     number: 2
     state: present
     part_type: primary
     part_start: 1024MiB
     part_end: 100% 
     flags: [ msftdata ]

- name: format efi boot grub filesystem
  become: yes
  filesystem:
    fstype: vfat
    dev: "{{ usb_device }}1"   

- name: format data partition filesystem
  become: yes
  filesystem:
    fstype: xfs
    dev: "{{ usb_device }}2"