---
# tasks file for qubinode-usb-imager
- name: install required packages
  include_tasks: install_pkgs.yml

- name: format qubinode boot partition 
  include_tasks: format_boot_partition.yml

- name: format qubinode data partition
  include_tasks: format_data_partition.yml

- name: deploy all files to usb partition
  include_tasks: configure_usb.yml

