---
# tasks file for qubinode-usb-imager
- name: install required packages
  include_tasks: install_pkgs.yml

- name: format qubinode boot partition 
  include_tasks: format_boot_partition.yml

- name: configure efi and legacy bootable partittion
  include_tasks: format_efi_partition.yml

- name: configure legacy bootable partition
  include_tasks: configure_usb.yml

