---
- hosts: satellite-server
  remote_user: root
  become: yes
  vars:
    packages:
      - grub2-efi 
      - shim 
      - gdisk 
      - grub2-efi-modules 
      - grub2-efi-x64-modules

    ks_file_dir: "{{ KS_FILE_DIR }}"
    rhel_iso_dir: "{{ RHEL_ISO_DIR }}"
    usb_device: "{{ USB_DEVICE }}"

  tasks:
    - name: install required packages
      yum: 
        name: "{{ usb_device }}"
        state: present
        
    - name: read usb device information 
      parted: 
        device: "{{ usb_device }}"
        unit: MiB
      register: disk_info

    -  name: remove all partitions from disk 
       parted:
         device: "{{ usb_device }}"
         number: "{{ item.num }}"
         state: absent
       with_items:
       - "{{ sdb_info.partitions }}"

    - name: tell the OS the paritions has change
      command: >
        sudo partprobe
      ignore_errors: True

    - name: create efi grub boot disk partition
      become: yes
      parted:
        label: msdos
        device: "{{ usb_device }}"
        number: 1
        state: present
        part_type: primary
        part_end: 1024MiB 
        flags: [ boot, esp ]

    - name: create data boot disk partition
      become: yes
      parted:
        label: msdos
        device: "{{ usb_device }}"
        number: 2
        state: present
        part_type: primary
        part_start: 1024MiB
        part_end: 100% 

    - name: format efi boot grub filesystem
      become: yes
      filesystem:
        fstype: vfat
        dev: "{{ usb_device }}1"   

    - name: format data partition filesystem
      become: yes
      filesystem:
        fstype: xfs
        dev: "{{ usb_device }}2"
    
    - name: create usb device mounting directory
      become: yes
      file:
          path: "{{ item }}"
          state: directory
          mode: '0755'
      with_items:
        - '/mnt/qubiusb/efi'
        - '/mnt/qubiusb/data'
    
    - name: mount efi filesystem
      become: yes
      mount:
        path: '/mnt/qubiusb/efi'
        src: "{{ usb_device }}1"  
        fstype: vfat
        state: present

    - name: mount data filesystem
      become: yes
      mount:
        path: '/mnt/qubiusb/data'
        src: "{{ usb_device }}2"  
        fstype: xfs
        state: present
  
    - name: install legacy grub system 
      become: yes
      command: >
        "grub2-install 
        --boot-directory='/mnt/qubiusb/data/boot'
        --target=i386-pc 
        --recheck 
        {{ usb_device }}" 
      
    - name: install efi grub system 
      become: yes
      command: >
        "grub2-install 
        --boot-directory='/mnt/qubiusb/data/boot'
        --efi-directory='/mnt/qubiusb/efi'
        --target=x86_64-efi 
        --bootloader-id=qubinode 
        --recheck
        --removable"

    - name:  

